[package]
name = "sandesh"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"
colored = "2.0"
rand = "0.8"
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
anyhow = "1.0"
byteorder = "1.4"
